// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeRQL7IRN5jQSYryQzd8M8Gi_YokFSJX8',
    appId: '1:433797492705:android:e538aa84ddb0b30eceeca0',
    messagingSenderId: '433797492705',
    projectId: 'exam-6-modul',
    databaseURL: 'https://exam-6-modul-default-rtdb.firebaseio.com',
    storageBucket: 'exam-6-modul.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPLHqHdauQlWqw5y4VT-2IhI-aZRh8bms',
    appId: '1:433797492705:ios:1bada0f897062e33ceeca0',
    messagingSenderId: '433797492705',
    projectId: 'exam-6-modul',
    databaseURL: 'https://exam-6-modul-default-rtdb.firebaseio.com',
    storageBucket: 'exam-6-modul.appspot.com',
    iosClientId: '433797492705-ck63imo6nfmfheof5fra4m9fp71m450p.apps.googleusercontent.com',
    iosBundleId: 'com.example.examSixModul',
  );
}
